<?php

return [
    7670946 => ['Ngaoundal','Tibati'],
    7670947 => ['Galim-Tignère','Kontcha','Mayo-Baléo','Tignère'],
    9224946 => ['Bankim','Banyo','Mayo-Darlé'],
    8299279 => ['Dir','Djohong','Meiganga','Ngaoui'],
    7670948 => ['Belel','Martap','Mbe','Nganha','Ngaoundéré 1er','Ngaoundéré 2e','Ngaoundéré 3e','Nyambaka'],

    2229546 => ['Batchenga','Ebebda','Elig-Mfomo','Evodoula','Lobo','Monatélé','Obala','Okola','Sa\'a'],
    9224948 => ['Bafia','Bokito','Deuk','Kiiki','Kon-Yambetta','Makénéné','Ndikiniméki','Nitoukou','Ombessa'],
    7730793 => ['Mbangassina','Ngambè-Tikar','Ngoro','Ntui','Yoko'],
    9165815 => ['Akono','Bikok','Mbankomo','Ngoumou'],
    8693008 => ['Yaoundé 1er','Yaoundé 2e','Yaoundé 3e','Yaoundé 4e','Yaoundé 5e','Yaoundé 6e','Yaoundé 7e'],
    7731690 => ['Afanloum','Assamba','Awaé','Edzendouan','Esse','Mfou','Nkolafamba','Soa'],
    2223330 => ['Biyouha','Bondjock','Bot-Makak','Dibang','Éséka','Makak','Matomb','Messondo','Ngog-Mapubi','Nguibassal'],
    2223329 => ['Akonolinga','Ayos','Endom','Mengang','Nyakokombo'],
    2223327 => ['Akoeman','Dzeng','Mbalmayo','Mengueme','Ngomedzap','Nkolmetet'],
    2230817 => ['Bibey','Lembe-Yezoum','Mbandjock','Minta','Nanga-Eboko','Nkoteng','Nsem'],

    2233500 => ['Gari-Gombo','Moloundou','Salapoumbé','Yokadouma'],
    2230815 => ['Abong-Mbang','Bebend','Dimako','Dja','Doumaintang','Doumé','Lomié','Mboanz','Mboma','Messamena','Messok','Ngoyla','Nguelemendouka','Somalomo'],
    2230606 => ['Batouri','Bombé','Kette','Mbang','Mbotoro','Ndelele','Ndem-Nam'],
    2229251 => ['Bélabo','Bertoua 1er','Bertoua 2e','Bétaré-Oya','Diang','Garoua-Boulaï','Mandjou','Ngoura'],

    2233122 => ['Bogo','Dargala','Gazawa','Maroua 1er','Maroua 2e','Maroua 3e','Meri','Ndoukoula','Petté'],
    2229291 => ['Blangoua','Darak','Fotokol','Goulfey','Hile-Alifa','Kousseri','Logone-Birni','Makary','Waza','Zina'],
    2228217 => ['Datcheka','Gobo','Guéré','Kaï-Kaï','Kalfou','Kar-Hay','Maga','Tchati-Bali','Vele','Wina','Yagoua'],
    7932539 => ['Guidiguis','Kaélé','Mindif','Moulvoudaye','Moutourwa','Porhi','Taibong'],
    9224949 => ['Kolofata','Mora','Tokombéré'],
    9224951 => ['Bourrha','Hina','Koza','Mayo-Moskota','Mogode','Mokolo','Soulédé-Roua'],

    2225744 => ['Abo-Fiko','Baré-Bakem','Dibombari','Loum','Manjo','Mbanga','Melong','Mombo','Njombe-Penja','Nkongsamba 1er','Nkongsamba 2e','Nkongsamba 3e','Nlonako'],
    2224165 => ['Nkondjock','Nord-Makombé','Yabassi','Yingui'],
    2222269 => ['Dibamba','Dizangué','Édéa 1er','Édéa 2e','Massock-Songloulou','Mouanko','Ndom','Ngambe','Ngwei','Nyanon','Pouma'],
    2221059 => ['Douala 1er','Douala 2e','Douala 3e','Douala 4e','Douala 5e','Douala 6e'],

    2234396 => ['Baschéo','Bibemi','Dembo','Demsa','Garoua 1er','Garoua 2e','Garoua 3e','Lagdo','Mayo-Hourna','Pitoa','Tcheboa','Touroua'],
    9228189 => ['Beka','Poli'],
    8740152 => ['Figuil','Guider','Mayo-Oulo'],
    8740150 => ['Madingring','Rey-Bouba','Tcholliré','Touboro'],

    2234988 => ['Babadjou','Batcham','Galim','Mbouda'],
    2227064 => ['Dschang','Fokoué','Fongo-Tongo','Nkong-Ni','Penka-Michel','Santchou'],
    2225334 => ['Bangangté','Bassamba','Bazou','Tonga'],
    2230816 => ['Bafang','Bakou','Bana','Bandja','Banka','Banwa','Kékem'],
    9224961 => ['Baham','Bamendjou','Bangou','Batié'],
    9224964 => ['Bayangam','Djebem','Poumougne'],
    2226712 => ['Bafoussam 1er','Bafoussam 2e','Bafoussam 3e'],
    9224965 => ['Bangourain','Foumban','Foumbot','Kouoptamo','Koutaba','Magba','Malentouen','Massangam','Njimom'],

    9224959 => ['Belo','Bum','Fundong','Njinikom'],
    2233408 => ['Jakiri','Kumbo','Mbven','Nkum','Noni','Oku'],
    2232640 => ['Ako','Misaje','Ndu','Nkambé','Nwa'],
    2226947 => ['Fungom','Furu-Awa','Menchum Valley','Wum'],
    2226830 => ['Bafut','Bali','Bamenda 1er','Bamenda 2e','Bamenda 3e','Santa','Tubah'],
    2226140 => ['Batibo','Mbengwi','Ngie','Njikwa','Widikum-Menka'],
    10289311 => ['Babessi','Balikumbat','Ndop'],

    2232969 => ['Bengbis','Djoum','Meyomessala','Meyomessi','Mintom','Oveng','Sangmélima','Zoétélé'],
    2229760 => ['Akom 2','Bipindi','Campo','Kribi 1er','Kribi 2e','Lokoundjé','Lolodorf','Mvengue','Niete'],
    9230015 => ['Biwong-Bane','Biwong-Bulu','Ebolowa 1er','Ebolowa 2e','Efoulan','Mengong','Mvangan','Ngoulemakong'],
    9239012 => ['Ambam','Kyé-Ossi','Ma\'an','Olamze'],

    2231710 => ['Buea','Limbé 1er','Limbé 2e','Limbé 3e','Muyuka','Tiko','West Coast'],
    8505106 => ['Bangem','Nguti','Tombel'],
    9224975 => ['Alou','Fontem','Wabane'],
    2228442 => ['Akwaya','Eyumodjock','Mamfé Central','Upper Banyang'],
    2227197 => ['Konye','Kumba 1er','Kumba 2e','Kumba 3e','Mbonge'],
    2225280 => ['Bamusso','Dikome-Balue','Ekondo-Titi','Idabato','Isanguele','Kombo-Abedimo','Kombo-Itindi','Mundemba','Toko'],
];
